AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Tables for Barter Exchange Platform

Resources:

  ### USERS TABLE ###
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: phone_number
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PhoneLookupIndex
          KeySchema:
            - AttributeName: phone_number
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ### ITEMS TABLE ###
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Items
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: item_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: item_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserItemsIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ### BIDS TABLE ###
  BidsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bids
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bid_id
          AttributeType: S
        - AttributeName: requested_user_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: offered_by
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: bid_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ReceivedBidsIndex
          KeySchema:
            - AttributeName: requested_user_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: OfferedBidsIndex
          KeySchema:
            - AttributeName: offered_by
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
    Export:
      Name: UsersTableName

  ItemsTableName:
    Value: !Ref ItemsTable
    Export:
      Name: ItemsTableName

  BidsTableName:
    Value: !Ref BidsTable
    Export:
      Name: BidsTableName

